name: bChatManager
main: net.rymate.bchatmanager.bChatManager
depend: [ Vault ]
softdepend: [ Factions, Multiverse-Core]
version: 4.0.0
author: rymate1234
website: www.rymate.co.uk
description: Chat management plugin for bPermissions based of PEX ChatManager
commands:
  me:
    description: Sends a message in the third person!
    usage: /me <message>
  bchatreload:
    description: Reloads bChatManager
    usage: /bchatreload
